//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: central.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Central_CentralClient`, then call methods of this protocol to make API calls.
public protocol Central_CentralClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Central_CentralClientInterceptorFactoryProtocol? { get }

  func sendReportToken(
    _ request: Central_ReportToken,
    callOptions: CallOptions?
  ) -> UnaryCall<Central_ReportToken, Central_Ack>

  func pollPositive(
    _ request: Central_Date,
    callOptions: CallOptions?
  ) -> UnaryCall<Central_Date, Central_Batch>

  func pollNegative(
    _ request: Central_Date,
    callOptions: CallOptions?
  ) -> UnaryCall<Central_Date, Central_Batch>
}

extension Central_CentralClientProtocol {
  public var serviceName: String {
    return "central.Central"
  }

  /// Unary call to sendReportToken
  ///
  /// - Parameters:
  ///   - request: Request to send to sendReportToken.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func sendReportToken(
    _ request: Central_ReportToken,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Central_ReportToken, Central_Ack> {
    return self.makeUnaryCall(
      path: "/central.Central/sendReportToken",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makesendReportTokenInterceptors() ?? []
    )
  }

  /// Unary call to pollPositive
  ///
  /// - Parameters:
  ///   - request: Request to send to pollPositive.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func pollPositive(
    _ request: Central_Date,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Central_Date, Central_Batch> {
    return self.makeUnaryCall(
      path: "/central.Central/pollPositive",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makepollPositiveInterceptors() ?? []
    )
  }

  /// Unary call to pollNegative
  ///
  /// - Parameters:
  ///   - request: Request to send to pollNegative.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func pollNegative(
    _ request: Central_Date,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Central_Date, Central_Batch> {
    return self.makeUnaryCall(
      path: "/central.Central/pollNegative",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makepollNegativeInterceptors() ?? []
    )
  }
}

public protocol Central_CentralClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'sendReportToken'.
  func makesendReportTokenInterceptors() -> [ClientInterceptor<Central_ReportToken, Central_Ack>]

  /// - Returns: Interceptors to use when invoking 'pollPositive'.
  func makepollPositiveInterceptors() -> [ClientInterceptor<Central_Date, Central_Batch>]

  /// - Returns: Interceptors to use when invoking 'pollNegative'.
  func makepollNegativeInterceptors() -> [ClientInterceptor<Central_Date, Central_Batch>]
}

public final class Central_CentralClient: Central_CentralClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Central_CentralClientInterceptorFactoryProtocol?

  /// Creates a client for the central.Central service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Central_CentralClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Central_CentralProvider: CallHandlerProvider {
  var interceptors: Central_CentralServerInterceptorFactoryProtocol? { get }

  func sendReportToken(request: Central_ReportToken, context: StatusOnlyCallContext) -> EventLoopFuture<Central_Ack>

  func pollPositive(request: Central_Date, context: StatusOnlyCallContext) -> EventLoopFuture<Central_Batch>

  func pollNegative(request: Central_Date, context: StatusOnlyCallContext) -> EventLoopFuture<Central_Batch>
}

extension Central_CentralProvider {
  public var serviceName: Substring { return "central.Central" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "sendReportToken":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Central_ReportToken>(),
        responseSerializer: ProtobufSerializer<Central_Ack>(),
        interceptors: self.interceptors?.makesendReportTokenInterceptors() ?? [],
        userFunction: self.sendReportToken(request:context:)
      )

    case "pollPositive":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Central_Date>(),
        responseSerializer: ProtobufSerializer<Central_Batch>(),
        interceptors: self.interceptors?.makepollPositiveInterceptors() ?? [],
        userFunction: self.pollPositive(request:context:)
      )

    case "pollNegative":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Central_Date>(),
        responseSerializer: ProtobufSerializer<Central_Batch>(),
        interceptors: self.interceptors?.makepollNegativeInterceptors() ?? [],
        userFunction: self.pollNegative(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Central_CentralServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'sendReportToken'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makesendReportTokenInterceptors() -> [ServerInterceptor<Central_ReportToken, Central_Ack>]

  /// - Returns: Interceptors to use when handling 'pollPositive'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makepollPositiveInterceptors() -> [ServerInterceptor<Central_Date, Central_Batch>]

  /// - Returns: Interceptors to use when handling 'pollNegative'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makepollNegativeInterceptors() -> [ServerInterceptor<Central_Date, Central_Batch>]
}
